name: CI

on:
  push:
    branches: [master]

jobs:
  package-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: chrislennon/action-aws-cli@1.1

      - name: Prepare prerelease semantic
        if: github.ref != 'refs/heads/master'
        run: |
          mv .releaserc.prerelease .releaserc

      - name: Using .releaserc.yaml
        run: |
          cat .releaserc.yaml

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.0
        id: semantic
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/changelog@5
            @semantic-release/exec@5
            @semantic-release/git@9
        env:
          GITHUB_TOKEN: ${{ github.token }}
